services:
  mysql:
    image: mysql:8.0
    container_name: lampada_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lampada_iot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  grafana:
    image: grafana/grafana:latest
    container_name: lampada_grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  mysql_data:
  grafana_data:
